from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from decimal import Decimal
import uuid

from backend.src.db.session import get_db
from backend.src.db.models import Transaction, User
from backend.src.core.ledger import LedgerEngine

# Router mapped with futuristic Star Trek sub-space tactical layout descriptors
router = APIRouter(prefix="/warp-core/fuel", tags=["Antimatter Fuel Injector (EUR Deposits)"])

class SEPADepositRequest(BaseModel):
    """
    Validates cross-border incoming Euro telemetry data from Sector 01 (Europe).
    """
    user_id: uuid.UUID = Field(..., description="The Starfleet Identity Registry ID of the user pocket")
    sender_iban: str = Field(..., description="The European banking routing line matrix (IBAN)")
    deposit_amount_eur: Decimal = Field(..., gt=0, description="The total volume of Euro energy to inject")
    subspace_clearance_key: str = Field(..., description="Unique transaction UUID generated by the bridge app console")


class FuelInjectionResponse(BaseModel):
    status: str
    injector_id: str
    volume_added: float
    currency: str
    target_sector: str
    message: str


@router.post("/inject-euro", response_model=FuelInjectionResponse)
def inject_euro_funds(payload: SEPADepositRequest, db: Session = Depends(get_db)):
    """
    Processes an inbound SEPA Instant credit transfer to fuel the wallet with Euros.
    Verifies regional compliance status before authorizing the intake valve.
    """
    # 1. Verify if user is registered in the sector database and passes security check
    user_profile = db.query(User).filter_by(user_id=payload.user_id).first()
    if not user_profile:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The targeted Starfleet Identity record does not exist in this sector."
        )

    if user_profile.eu_compliance_status != "APPROVED":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Sub-space clearance check failed. European compliance status is not APPROVED."
        )

    # 2. Block redundant replay hits (Idempotency verification)
    existing_txn = db.query(Transaction).filter_by(reference_id=payload.subspace_clearance_key).first()
    if existing_txn:
        return FuelInjectionResponse(
            status="CONNECTED",
            injector_id=str(existing_txn.transaction_id),
            volume_added=float(existing_txn.source_amount),
            currency=existing_txn.source_currency,
            target_sector="SECTOR_01_EUROPE",
            message="Telemetry duplicate recognized. Euro fuel reserves are already safely docked."
        )

    # 3. Open intake valve: Pass data to LedgerEngine to update the EUR pocket balance
    ledger_result = LedgerEngine.deposit_funds(
        db_session=db,
        user_id=payload.user_id,
        amount=payload.deposit_amount_eur,
        currency="EUR",
        reference_id=payload.subspace_clearance_key
    )

    if ledger_result["status"] == "FAILED":
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Warp Core integration error: {ledger_result['reason']}"
        )

    # Pull the confirmed transaction ticket from database logs
    confirmed_txn = db.query(Transaction).filter_by(reference_id=payload.subspace_clearance_key).one()

    return FuelInjectionResponse(
        status="STABILIZED",
        injector_id=str(confirmed_txn.transaction_id),
        volume_added=float(confirmed_txn.target_amount),
        currency="EUR",
        target_sector="SECTOR_01_EUROPE",
        message="Euro fuel cells safely contained. Warp core energy at 100% capacity."
    )
