from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from decimal import Decimal
import uuid

from backend.src.db.session import get_db
from backend.src.db.models import Transaction, ExchangeRateCache
from backend.src.core.ledger import LedgerEngine

router = APIRouter(prefix="/fx", tags=["Foreign Exchange Engine"])

class FXConversionRequest(BaseModel):
    user_id: uuid.UUID = Field(..., description="The platform UUID of the user converting money")
    source_currency: str = Field("EUR", description="The currency wallet to debit")
    target_currency: str = Field("THB", description="The currency wallet to credit")
    source_amount: Decimal = Field(..., gt=0, description="The total amount of source currency to spend")
    idempotency_key: str = Field(..., description="Unique transaction UUID generated by the mobile client")


class FXConversionResponse(BaseModel):
    status: str
    debited_amount: float
    source_currency: str
    credited_amount: float
    target_currency: str
    exchange_rate: float
    reference_id: str


@router.get("/rate", response_model=dict)
def get_live_rate(from_currency: str = "EUR", to_currency: str = "THB", db: Session = Depends(get_db)):
    """
    Fetches the current customer-facing conversion rate including the platform spread markup.
    Use this to show the conversion preview screen on the mobile app.
    """
    rate_meta = db.query(ExchangeRateCache).filter_by(
        from_currency=from_currency, to_currency=to_currency
    ).first()

    if not rate_meta:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Currency pair {from_currency}/{to_currency} is currently unavailable."
        )

    # Calculate rate after taking out our platform fee markup margin
    client_rate = rate_meta.mid_market_rate * (Decimal('1.0') - rate_meta.fee_markup_percent)
    
    return {
        "from_currency": from_currency,
        "to_currency": to_currency,
        "mid_market_rate": float(rate_meta.mid_market_rate),
        "client_rate": float(client_rate),
        "markup_percent": float(rate_meta.fee_markup_percent * 100)
    }


@router.post("/convert", response_model=FXConversionResponse)
def convert_currency(payload: FXConversionRequest, db: Session = Depends(get_db)):
    """
    Executes an atomic conversion from one currency pocket to another (e.g., EUR to THB).
    Guarded by an idempotency check to avoid double conversions due to laggy mobile networks.
    """
    # 1. Enforce strict Idempotency protection
    existing_txn = db.query(Transaction).filter_by(reference_id=payload.idempotency_key).first()
    if existing_txn:
        return FXConversionResponse(
            status="SUCCESS",
            debited_amount=float(existing_txn.source_amount),
            source_currency=existing_txn.source_currency,
            credited_amount=float(existing_txn.target_amount),
            target_currency=existing_txn.target_currency,
            exchange_rate=float(existing_txn.applied_rate),
            reference_id=existing_txn.reference_id
        )

    # 2. Call the ledger engine to swap balances safely
    result = LedgerEngine.execute_fx_exchange(
        db_session=db,
        user_id=payload.user_id,
        source_currency=payload.source_currency,
        target_currency=payload.target_currency,
        source_amount=payload.source_amount,
        reference_id=payload.idempotency_key
    )

    # 3. Handle structural execution outputs
    if result["status"] == "FAILED":
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"FX Engine execution failed: {result['reason']}"
        )

    return FXConversionResponse(
        status="SUCCESS",
        debited_amount=result["debited"],
        source_currency=payload.source_currency,
        credited_amount=result["credited"],
        target_currency=payload.target_currency,
        exchange_rate=result["rate_applied"],
        reference_id=payload.idempotency_key
    )
