from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from decimal import Decimal
import uuid

from backend.src.db.session import get_db
from backend.src.db.models import Transaction, User
from backend.src.core.ledger import LedgerEngine

router = APIRouter(prefix="/qr", tags=["QR Merchant Payments"])

class QRDecodeRequest(BaseModel):
    """
    Validates incoming payload details sent directly by the smartphone app's scanner.
    """
    sender_id: uuid.UUID = Field(..., description="The internal platform UUID of the user making the purchase")
    merchant_proxy_value: str = Field(..., description="The parsed phone number, Tax ID, or account number from the QR string")
    amount: Decimal = Field(..., gt=0, description="The payment total specified in Thai Baht")
    currency: str = Field("THB", description="The settlement currency profile")
    idempotency_key: str = Field(..., description="Unique transaction UUID generated by the app to block duplicate processing hits")


class PaymentResponse(BaseModel):
    status: str
    transaction_id: str
    reference_id: str
    amount_paid: float
    currency: str
    message: str


@router.post("/process-merchant-payment", response_model=PaymentResponse)
def process_merchant_payment(payload: QRDecodeRequest, db: Session = Depends(get_db)):
    """
    Validates and executes an instant local transaction triggered by scanning an EMVCo Thai QR code.
    Checks for network replay attacks via Idempotency standard before moving funds.
    """
    # 1. Enforce strict Idempotency protection to secure against double-spend cellular glitches
    existing_txn = db.query(Transaction).filter_by(reference_id=payload.idempotency_key).first()
    if existing_txn:
        if existing_txn.status == "SUCCESS":
            return PaymentResponse(
                status="SUCCESS",
                transaction_id=str(existing_txn.transaction_id),
                reference_id=existing_txn.reference_id,
                amount_paid=float(existing_txn.target_amount),
                currency=existing_txn.target_currency,
                message="Duplicate request detected. Transaction was already successfully settled."
            )
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="A pending or failed transaction with this reference key already exists."
            )

    # 2. Look up the designated pseudo merchant profile inside the local environment
    # In production, this matches the QR's proxy data to a registered merchant account row
    merchant_user = db.query(User).filter(
        (User.full_name == payload.merchant_proxy_value) | 
        (User.thai_compliance_status == "APPROVED")
    ).first()

    if not merchant_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The targeted Thai merchant network proxy could not be verified on our rails."
        )

    # 3. Pass processing to the database ledger engine block
    ledger_result = LedgerEngine.process_p2p_payment(
        db_session=db,
        sender_id=payload.sender_id,
        receiver_id=merchant_user.user_id,
        amount=payload.amount,
        currency=payload.currency,
        reference_id=payload.idempotency_key
    )

    # 4. Handle structural execution outputs
    if ledger_result["status"] == "FAILED":
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Ledger engine execution failed: {ledger_result['reason']}"
        )

    # Find the newly created transaction block to return the hardware ID
    confirmed_txn = db.query(Transaction).filter_by(reference_id=payload.idempotency_key).one()

    return PaymentResponse(
        status="SUCCESS",
        transaction_id=str(confirmed_txn.transaction_id),
        reference_id=confirmed_txn.reference_id,
        amount_paid=float(confirmed_txn.target_amount),
        currency=confirmed_txn.target_currency,
        message="Payment to local merchant settled successfully via Swap-V1 engine."
    )
